version: 0.2

phases:
install:
commands:
- echo Installing dependencies...
- pip install -r requirements.txt
build:
commands:
- echo Build started on date
- echo Compressing application files...
- zip -r app_package.zip ./*
post_build:
commands:
- echo Build completed on date
artifacts:
files:
- app_package.zip
- appspec.yml
- app.py
- requirements.txt
